server:
  port: 5101
  servlet:
    context-path: /xgt
spring:
  profiles:
    active: prd  #设置部署环境
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB #文件上传单个文件最大值
      max-request-size: 100MB #文件上传文件总大小
  main:
    allow-bean-definition-overriding: true
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://localhost:3306/xgtprd?useUnicode=true&useSSL=false&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: root
      password: nic@1234
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  redis:
    host: 127.0.0.1
    port: 6376
    password: nic@1234
    timeout: 30000
    database: 0 #正式库

#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html

#mybatise配置
mybatis:
  #  typeAliasesPackage: com.nic.xgt.web.entity,com.nic.xgt.web.model
  #  mapperLocations: classpath:com/nic/xgt/web/dao/*.xml
  config-location: classpath:mybatis-config.xml

#自定义文件上传配置
file:
  virtualPath: /uploadImg/   #虚拟路径，结尾必须加上"/"
  uploadFolder: /home/java/xgt/upload/   #附件上传目录，结尾必须加上"/"
  exportPath: /home/java/xgt/export/  #导出文件存放路劲，结尾必须加上"/"
  templatePath: /home/java/xgt/upload/template/   #模板文件路径，结尾必须加上"/"

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

logging:
  path:
    ./logs
  config:
    classpath:logback-spring.xml
  level:
    org.thymeleaf: info

#是否开启Knife4j文档
swagger:
  enable: false
